global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kong'
    metrics_path: /metrics
    static_configs:
      - targets: ['kong:8001']   # use 'localhost:8001' if running outside Docker
